apiVersion: batch/v1
kind: CronJob
metadata:
  name: grpcgoonch-headless-multiclient-pickfirst-cron
  labels:
    app: grpcgoonch-headless-multiclient-pickfirst
spec:
  schedule: "0/8 * * * *"
  jobTemplate:
    metadata:
      labels:
        app: grpcgoonch-headless-multiclient-pickfirst
    spec:
      template:
        spec:
          containers:
          - name: grpcgoonch-headless-multiclient-pickfirst
            image: thaigoonch/grpcgoonch-headless-multiclient-pickfirst:1.1
            imagePullPolicy: IfNotPresent
            env:
            - name: LOG_LEVEL
              value: "DEBUG"
          restartPolicy: Never
          nodeSelector:
            goonchrole: "nonserver"